---
- hosts: new_server 
  become: yes

  vars:
    ssh_key_filename: ~/.ssh/id_rsa
    new_user: sulai

  vars_prompt:
    - name: new_host_name
      promt: enter a new hostname for the device
      private: no

  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes

  - name: set hostname
    hostname:
      name: "{{new_host_name}}" 

  - name: Ensure group exists
    group:
      name: "{{new_user}}"
      state: present

  - name: Add the user with a bash shell, appending the group root to the user's groups
    user:
      name: "{{new_user}}"
      shell: /bin/bash
      group: "{{new_user}}"
      groups: "root,sudo"

  - name: Allow  group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%{{new_user}}'
      line: '%{{new_user}} ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Add provision user to the sudoers
    copy:
      dest: "/etc/sudoers.d/{{new_user}}"
      content: "{{new_user}} ALL=(ALL) NOPASSWD: ALL"

  - name: Deploy SSH Key
    ansible.posix.authorized_key: 
      user: "{{new_user}}"
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCk/ADaCThTMmFCMwFV/jaOer2evZZlmo2DUKKCSl7s+t5uyuEQIbd1uJ5pZQKUAlkQ9M+YmiCrEqCzGGNVllRqHCqaLutkifLSdyFQv9OZ8vlMtzmXrXL/t+mpF080231it1VQ5jFXu29jplS37t3IdZcC17FldthMwDThdLl2re3gIMgVxdaIHGDAArIoen//7JczadHdLsMCetv+++zZWod23/EgAu6j3nk4gSuL99lCjPSZN5YXqlqpFynkINsANkUmMCpHj8TO02s8iNj0P1aFghn8PtnRsZw5iVuQHG3ISxSjhjVAVJRVsNYE5RVsQ3GdfkgASvzUylaWUxiV1yM4YvhO1LjKKI5aNwKJdvjpdCyPUcckrnbsAdbdt2yBQjX/JALcfVhbdCMRYqGiwUvE8fvWA69Mf4y9iAa9xPRoyYVpfHgpH3CfCVfSld0+iYi+7bXi6ylQDndO5jvWUGvamL7YCvn75MBnq4IDWSn2Daj6ny2dArUgOZxiFls= sulai@DESKTOP-I2L75NN"
      state: present

  - name: Disable Password Authentication
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: "PasswordAuthentication no"
      state: present
      backup: yes
  
  - name: Disable Root Login
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: "PermitRootLogin no"
      state: present
      backup: yes
    notify:
      - restart ssh

  - name: Ensure net-tools are installed
    yum: name=net-tools state=present

  - name: Ensure wireless-tools are installed
    yum: name=wireless-tools state=present

  - name: Configure WIFI
    copy:
      src: ../etc/netplan/50-cloud-init.yaml
      dest: /etc/netplan/50-cloud-init.yaml
      owner: root
      group: root
      mode: 0640

  - name: start netplan
    become: true
    shell: 
      netplan --debug generate
      netplan apply
      netplan try

  - name : reboot
    reboot:

  handlers:
    - name: restart ssh
      service:
        name=sshd
        state=restarted
